name: Update SDK & Network

on:
  workflow_dispatch:

  push:
    branches:
      - "stable"


permissions:
  contents: write


jobs:

  update-sdk:

    runs-on: ubuntu-latest

    steps:

      - name: Clone SDK fork repository
        uses: actions/checkout@v4
        with:
          clean: true
          repository: "Tamerti/open.mp-sdk-test"
          path: "SDK"
          ref: "master"
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}


      - name: Sync SDK fork
        shell: bash
        run: |
          cd SDK

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout master

          git pull origin master

          git push origin master



  update-network:

    runs-on: ubuntu-latest

    steps:

      - name: Clone open.mp Network repository
        uses: actions/checkout@v4
        with:
          clean: true
          repository: "openmultiplayer/open.mp-network"
          path: "Network"
          ref: "master"
          submodules: recursive


      - name: Sync Network source
        shell: bash
        run: |
          cd Network

          git checkout master

          git fetch origin

          git pull origin master
